### ISSUE TITLE
Generate() is not working in Unity 2023.2.6f1

### ISSUE THREAD

**Issue by rillwvy** [ruccho/FangAutoTile#2]
After Generate() is executed, FangAutoTile’s combinations return to the initial value. It seems to work normally if serializedObject.ApplyModifiedProperties() is called before AssetDatabase.SaveAssets().

*It works normally in 2021.3.34f1.

**Comment by flypart** [comment]
2022.3.17

FangAutoTileEditor.cs
Line 338, add **_serializedObject.ApplyModifiedProperties();_**

```
finally
{
    serializedObject.ApplyModifiedProperties();
    AssetDatabase.SaveAssets();
    AssetDatabase.Refresh();
    AssetDatabase.ImportAsset(AssetDatabase.GetAssetPath(target));

    serializedObject.ApplyModifiedProperties();
}
```
