### ISSUE TITLE
Generate! message and Clear assets not working in Unity 2022.3.17f1

### ISSUE THREAD

**Issue by PhilipeFernandino** [ruccho/FangAutoTile#3]
Repro: 
In Unity 2022.3.17f1, with the package installed and a 64 * 320 Texture (probably not important, but I haven't tested with other sizes).

1. The Fang Auto Tile asset TextBox says "No tiles generated" after successfully generating the texture.
2. The same asset is not deleting the generated textures when running the "Clear all generated contents" and confirming in the prompt.

As there's no open discussion on this repo (and this might also be an error), should the asset also generate a Rule Tile or the user has to make one after the tiles are generated so the Tilemap Editor behave as in the examples?

**Comment by ruccho** [comment]
Thank you for reporting! The issue is fixed and merged.

> should the asset also generate a Rule Tile or the user has to make one after the tiles are generated so the Tilemap Editor behave as in the examples?

You don't have to generate a Rule Tile (included in 2d-extras?)
After you click a generate button on the inspector of Fang Auto Tile asset, you can simply place the asset on the tile editor window and it behaves like a rule tile.
